version: "3"

services:
  back-end:
    build:
      context: backend
    container_name: back-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3001:3001"
    command: node app.js

  front-end:
    build:
      context: frontend
    container_name: front-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm start

networks:
  node-network:
    driver: bridge
